import "./globals.css";
import { Montserrat } from "next/font/google";
import Navbar from "./component/Navbar";
import Footer from "./component/Footer";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Gym Application",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
